# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: demo-app-affinity
#   labels:
#     app: demo-app
# spec:
#   replicas: 100
#   selector:
#     matchLabels:
#       app: demo-app
#   template:
#     metadata:
#       labels:
#         app: demo-app
#     spec:
#       affinity:
#         nodeAffinity:
#           requiredDuringSchedulingIgnoredDuringExecution:
#             nodeSelectorTerms:
#             - matchExpressions:
#               - key: disktype
#                 operator: In
#                 values:
#                 - ssd
#       containers:
#       - name: nginx
#         image: nginx
#         ports:
#         - containerPort: 80



mkdir -i